[phases.setup]
nixPkgs = ['bun']

[phases.install]
# We use 'cd .' to ensure we are in the context Nixpacks expects
cmds = ['cd . && bun install --frozen-lockfile']

[phases.build]
cmds = ['bun run build']

[start]
cmd = 'bun run start'